version: "3"

services:
  # jupyterlab with pyspark
  pyspark:
    image: jupyter/pyspark-notebook
    container_name:  pyspark
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "martin"
    ports:
      - "10000:8888"
    volumes:
      - ./data:/home/jovyan/data
      - ./dev:/home/jovyan/dev
    networks:
      - local

volumes:
  data:
  dev:
networks:
  local:
    